# Generated by Django 3.1.7 on 2021-05-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
